SHOPEE_ORDER_STATUS_ENUM = ['COMPLETED', 'READY_TO_SHIP', 'RETRY_SHIP',
                            'SHIPPED', 'IN_CANCEL', 'CANCELLED', 'TO_RETURN']
LAZADA_ORDER_SYNC_TYPE = 'lazada_order'
SHOPEE_ORDER_SYNC_TYPE = 'shopee_order'
LAZADA_INVENTORY_SYNC_TYPE = 'lazada_inventory'
SHOPEE_INVENTORY_SYNC_TYPE = 'shopee_inventory'
ACCESS_SYNC_TYPE = 'access'
SYNC_SUCCESSFUL_STATUS = 'successful'
SYNC_PARTIALLY_SUCCESSFUL_STATUS = 'partially_successful'
SYNC_FAILED_STATUS = 'failed'
SHOPEE_INVENTORY_ITEM_THRESHOLD_IN_SECONDS = 86400
SHOPEE_LOGISTICS_STATUS_ENUM = ['NOT_START', 'REQUEST_CREATED', 'PICKUP_DONE', 'PICKUP_RETRY', 'PICKUP_FAILED'
                                'DELIVERY_DONE', 'DELIVERY_FAILED', 'REQUEST_CANCELED', 'COD_REJECTED', 'READY'
                                'INVALID', 'LOST', 'UNKNOWN']
