"""empty message

Revision ID: 06daf8bcbab4
Revises: a12463091fd4
Create Date: 2019-07-11 18:45:17.246005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06daf8bcbab4'
down_revision = 'a12463091fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_experience', 'artist_experience_application', ['user_id', 'experience_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_experience', 'artist_experience_application', type_='unique')
    # ### end Alembic commands ###
