"""empty message

Revision ID: 2b4c67f43632
Revises: af883c5cb573
Create Date: 2019-06-19 05:13:57.586585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4c67f43632'
down_revision = 'af883c5cb573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('email_subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'email_subject')
    # ### end Alembic commands ###
