"""empty message

Revision ID: 400e4dd70181
Revises: aafb0bbcdd0f
Create Date: 2019-07-01 11:48:19.113037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400e4dd70181'
down_revision = 'aafb0bbcdd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('experience', 'pincode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('experience', 'location')
    # ### end Alembic commands ###
