"""empty message

Revision ID: 8e70f2f40ee6
Revises: 92e11a818c9a
Create Date: 2019-06-18 16:49:46.409171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e70f2f40ee6'
down_revision = '92e11a818c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('user_v2', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_v2', sa.Column('pinterest', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('professional_talent', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('self_description', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('state', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('user_v2', sa.Column('zipcode', sa.String(), nullable=True))
    op.drop_column('user_v2', 'has_active_subscription')
    op.drop_column('user_v2', 'is_trialing')
    op.drop_column('user_v2', 'business_name')
    op.drop_column('user_v2', 'plan')
    op.drop_column('user_v2', 'username')
    op.drop_column('user_v2', 'phone')
    op.drop_column('user_v2', 'marketplace_id')
    op.drop_column('user_v2', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('marketplace_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('is_trialing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('has_active_subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user_v2', 'zipcode')
    op.drop_column('user_v2', 'youtube')
    op.drop_column('user_v2', 'twitter')
    op.drop_column('user_v2', 'state')
    op.drop_column('user_v2', 'self_description')
    op.drop_column('user_v2', 'professional_talent')
    op.drop_column('user_v2', 'pinterest')
    op.drop_column('user_v2', 'is_active')
    op.drop_column('user_v2', 'instagram')
    op.drop_column('user_v2', 'image')
    op.drop_column('user_v2', 'full_name')
    op.drop_column('user_v2', 'facebook')
    op.drop_column('user_v2', 'city')
    # ### end Alembic commands ###
