"""empty message

Revision ID: a12463091fd4
Revises: 400e4dd70181
Create Date: 2019-07-05 08:22:01.572942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12463091fd4'
down_revision = '400e4dd70181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_experience_application_experience_id_fkey', 'artist_experience_application', type_='foreignkey')
    op.drop_constraint('artist_experience_application_user_id_fkey', 'artist_experience_application', type_='foreignkey')
    op.create_foreign_key(None, 'artist_experience_application', 'user_v2', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artist_experience_application', 'experience', ['experience_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('buy_experience_experience_id_fkey', 'buy_experience', type_='foreignkey')
    op.create_foreign_key(None, 'buy_experience', 'experience', ['experience_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('email_log_user_id_fkey', 'email_log', type_='foreignkey')
    op.create_foreign_key(None, 'email_log', 'user_v2', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('experience_created_by_fkey', 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'user_v2', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reset_token_user_id_fkey', 'reset_token', type_='foreignkey')
    op.create_foreign_key(None, 'reset_token', 'user_v2', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reset_token', type_='foreignkey')
    op.create_foreign_key('reset_token_user_id_fkey', 'reset_token', 'user_v2', ['user_id'], ['id'])
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key('experience_created_by_fkey', 'experience', 'user_v2', ['created_by'], ['id'])
    op.drop_constraint(None, 'email_log', type_='foreignkey')
    op.create_foreign_key('email_log_user_id_fkey', 'email_log', 'user_v2', ['user_id'], ['id'])
    op.drop_constraint(None, 'buy_experience', type_='foreignkey')
    op.create_foreign_key('buy_experience_experience_id_fkey', 'buy_experience', 'experience', ['experience_id'], ['id'])
    op.drop_constraint(None, 'artist_experience_application', type_='foreignkey')
    op.drop_constraint(None, 'artist_experience_application', type_='foreignkey')
    op.create_foreign_key('artist_experience_application_user_id_fkey', 'artist_experience_application', 'user_v2', ['user_id'], ['id'])
    op.create_foreign_key('artist_experience_application_experience_id_fkey', 'artist_experience_application', 'experience', ['experience_id'], ['id'])
    # ### end Alembic commands ###
