"""empty message

Revision ID: aafb0bbcdd0f
Revises: cfc28f48002e
Create Date: 2019-06-28 16:48:34.412152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafb0bbcdd0f'
down_revision = 'cfc28f48002e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_experience_application', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_experience_application', 'about')
    # ### end Alembic commands ###
