"""empty message

Revision ID: bee44c417304
Revises: df12b65a6dbb
Create Date: 2019-06-21 05:43:03.900687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee44c417304'
down_revision = 'df12b65a6dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('epoch_last_updated_at', sa.Integer(), nullable=True))
    op.add_column('experience', sa.Column('last_updated_at', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('last_updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'last_updated_by')
    op.drop_column('experience', 'last_updated_at')
    op.drop_column('experience', 'epoch_last_updated_at')
    # ### end Alembic commands ###
