"""empty message

Revision ID: df12b65a6dbb
Revises: d729c682332e
Create Date: 2019-06-20 20:14:29.192771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df12b65a6dbb'
down_revision = 'd729c682332e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'created_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
                postgresql_using='created_by::integer')
    op.create_foreign_key(None, 'experience', 'user_v2', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.alter_column('experience', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
