"""empty message

Revision ID: fe56d0ed6d9e
Revises: 2b4c67f43632
Create Date: 2019-06-20 07:44:29.646190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe56d0ed6d9e'
down_revision = '2b4c67f43632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('user_v2', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user_v2', 'status')
    # ### end Alembic commands ###
